In [11]:
] activate ..

  Activating project at `~/Documents/repositories/ml-portfolio/migrograd.jl`


In [12]:
using micrograd

In [13]:
child1 = DifferentiableTensor(ones(3,3));
child2 = DifferentiableTensor([1., 2., 3.]);

In [14]:
a = child1 - child2

micrograd.BinaryOpTensor{Float64, 2, 1, 2, micrograd.AddOp{Float64}}([0.0 0.0 0.0; -1.0 -1.0 -1.0; -2.0 -2.0 -2.0], [0.0 0.0 0.0; 0.0 0.0 0.0; 0.0 0.0 0.0], DifferentiableTensor{Float64, 2}([1.0 1.0 1.0; 1.0 1.0 1.0; 1.0 1.0 1.0], [0.0 0.0 0.0; 0.0 0.0 0.0; 0.0 0.0 0.0]), micrograd.UnaryOpTensor{Float64, 1, micrograd.UnaryMinusOp{Float64}}([-1.0, -2.0, -3.0], [0.0, 0.0, 0.0], DifferentiableTensor{Float64, 1}([1.0, 2.0, 3.0], [0.0, 0.0, 0.0])))

In [15]:
a.val

3×3 Matrix{Float64}:
  0.0   0.0   0.0
 -1.0  -1.0  -1.0
 -2.0  -2.0  -2.0

In [16]:
a.grad = [ 1. 0. 0. ; 0. 1. 0. ; 0. 0. 1.]

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [17]:
backward!(a)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [18]:
child1.grad

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [23]:
a.child2.grad

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [24]:
backward!(a.child2)

3-element Vector{Float64}:
 -1.0
 -1.0
 -1.0

In [25]:
child2.grad

3-element Vector{Float64}:
 -1.0
 -1.0
 -1.0