In [1]:
] activate ..

  Activating project at `~/Documents/repositories/ml-portfolio/migrograd.jl`


In [2]:
using micrograd

[ Info: Precompiling micrograd [b196b0ec-54a6-41dc-8a1a-fd632d20b8bd]


In [3]:
child1 = DifferentiableTensor(ones(3,3));
child2 = DifferentiableTensor([1., 2., 3.]);

In [4]:
a = child1 + child2

micrograd.BinaryOpTensor{Float64, 2, 1, 2, micrograd.AddOp{Float64}}([2.0 2.0 2.0; 3.0 3.0 3.0; 4.0 4.0 4.0], [0.0 0.0 0.0; 0.0 0.0 0.0; 0.0 0.0 0.0], DifferentiableTensor{Float64, 2}([1.0 1.0 1.0; 1.0 1.0 1.0; 1.0 1.0 1.0], [0.0 0.0 0.0; 0.0 0.0 0.0; 0.0 0.0 0.0]), DifferentiableTensor{Float64, 1}([1.0, 2.0, 3.0], [0.0, 0.0, 0.0]))

In [5]:
a.val

3×3 Matrix{Float64}:
 2.0  2.0  2.0
 3.0  3.0  3.0
 4.0  4.0  4.0

In [6]:
a.grad = [ 1. 0. 0. ; 0. 1. 0. ; 0. 0. 1.]

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [7]:
backward(a)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [8]:
child1.grad

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [9]:
child2.grad

3-element Vector{Float64}:
 1.0
 1.0
 1.0